### PR TITLE
feat: implement search highlight

### LINKED ISSUE #96: Bolding Sections of Project That Contain Searchbar Contents
With #95 implementing a search bar, we can change sections of the project to signify where it lines up with what the user types into the search-bar!

### PR DESCRIPTION
**Pull request by ansh-saini**
Fixes #96

I'm using the browser built-in [mark tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark) to achieve the highlight. This will ensure standard behaviour on all operating systems.

Here's a screenshot of how it looks:
image

### CODE REVIEW

**Comment by ansh-saini** [comment]
@snigdha-kansal Review please? :)

**Comment by ansh-saini** [comment]
@snigdha-kansal Did you get a chance to review this?

**Review by snigdha-kansal — COMMENTED** [review]
@ansh-saini sorry for the delay on this

one thing i observed: entering certain characters such as '\' '+' '*' '(' ')' or '?' in the search bar causes the app to crash
you can either reproduce it locally or at [deploy preview](<https://deploy-preview-205--opensource-acm-ucla.netlify.app/projects>)

other than that, it looks great to me! thanks so much for working on this 💯 
appreciate you improving naming and formatting where possible!

Yoda Very Good

**Comment by ansh-saini** [comment]
Thank you for the review @snigdha-kansal 
You found a great bug! I've fixed it.

**Comment by snigdha-kansal** [comment]
@ansh-saini It looks great, thanks!
One last thing: Can we remove match support if user enters just a single spacebar?

image

**Comment by ansh-saini** [comment]
Another great find @snigdha-kansal.
Thanks, I've resolved it.

**Review by snigdha-kansal — APPROVED** [review]
:shipit:

**Comment by ansh-saini** [comment]
Hey @snigdha-kansal Thank you for the approval.
Can you please also add the `hacktoberfest-accepted` label on this PR?

Also, just curious as to why you've approved it but not merged it yet. Is there something blocking the merge?

**Comment by snigdha-kansal** [comment]
@ansh-saini just added the label
oh i just thought you will like to merge it 😂 i can merge!

**Pull request merged**
