### PR TITLE
chore: update linters and clean out unnecessary config

### PR DESCRIPTION
**Pull request by BryanPan342**
* update linters
* removed prettier (i prefer optimizing later.. so in this case not having excess files like the prettier files if they are not used)

### CODE REVIEW

**Comment by mattxwang** [comment]
Oh wow, you're fast 🏃 

(gave you write permissions btw!)

Looks like it fails CI? But nbd

**Review by mattxwang — APPROVED** [review]
LGTM, feel free to do the honours!

(also, I ended up adding a newline-before-EOF style rule to the config y'all used in sunshine - is there a reason why it's not in the base config?)

**Comment by BryanPan342** [comment]
> before-EOF

honestly not sure.. it should be there.... hmmmmm

**Comment by mattxwang** [comment]
> > before-EOF
> 
> honestly not sure.. it should be there.... hmmmmm

Here's the relevant PR: https://github.com/uclaacm/website/pull/147

(rule is called `eol-last`)

**Pull request merged**
