### PR TITLE
fix: responsiveness

### LINKED ISSUE #202: Bug: Unresponsive Projects Page
## Issue 
The [Projects Page](https://opensource.uclaacm.com/projects) is currently not responsive on mobile view. The CSS layout becomes distorted causing elements to not display properly as shown below:

image
<>
image

## Proposed Solution
Implement responsive design using flexible units (e.g., %, vw, rem) and media queries to ensure the layout adapts to smaller screen sizes. Utilize Flexbox or CSS Grid to maintain proper element alignment and prevent overflow across all devices.

The projects should be laid out in a style similar to how it's done for the mobile view of [Team Page](https://www.uclaacm.com/officers) on the ACM @ UCLA Website.

A good resource to refer to would be the [intern training](https://github.com/uclaacm/centralized-intern-training).

### PR DESCRIPTION
**Pull request by ansh-saini**
Fixes #202 

## Screenshots
image

### CODE REVIEW

**Comment by ansh-saini** [comment]
@snigdha-kansal Hope this helps :)

**Review by snigdha-kansal — COMMENTED** [review]
hey @ansh-saini!
thanks so much for submitting this PR — it looks great!
i missed your comment on the issue since i wasn’t tagged
the issue was assigned to another officer @caitlynn-hauw so i’ve reached out to her to check if she's okay with moving forward with your PR!

Cat Apple

**Comment by ansh-saini** [comment]
@snigdha-kansal Any update on this?

**Comment by snigdha-kansal** [comment]
@ansh-saini unfortunately i'm still waiting on response from the officer

**Review by snigdha-kansal — APPROVED** [review]
she's good with merging this PR
:shipit:

**Comment by ansh-saini** [comment]
Awesome! 
Thank you for the approval. @snigdha-kansal 
Can you please also add the `hacktoberfest-accepted` label on this PR?

Also, just curious as to why you've approved it but not merged it yet. Is there something blocking the merge?

**Comment by snigdha-kansal** [comment]
@ansh-saini just added the label
same for this - i just thought you will like to merge it 😂 i can merge!

**Pull request merged**
