### PR TITLE
Filter repos in projects page by ucla-opensource tag

### PR DESCRIPTION
**Pull request by Amyh11325**
# What
Before, all repos and good first issues in the uclaacm org are shown on the projects page
After, only repos in the uclaacm org with the `ucla-opensource` topic are shown. And only good first issue topics inside repos with the `ucla-opensource` topic are shown.

# Why
Not all ucla acm repos are opensource and should be displayed on the website. Some repos are public but editors are limited to committee officers.

# Code Changes
Quick change, just filtered out all repos without the topic. 

# Testing Repos
1) Ran `yarn dev` and opened localhost
2) Went to the Projects page and checked that the projects listed there match all the projects that currently have the `ucla-opensource` topic in the uclaacm org

**Opensource Projects:**
Screen Shot 2024-02-05 at 7 44 13 PM

**Github Search**
Screen Shot 2024-02-05 at 7 44 46 PM

# Testing Good First Issues
1) Ran `yarn dev`
2) Went to `http://localhost:3000/contribute#good-first-issues` and checked that only repos with `ucla-opensource` topic are shown

**Before:**
Screen Shot 2024-02-22 at 6 38 12 PM

**After:**
Screen Shot 2024-02-22 at 6 37 24 PM

### CODE REVIEW

**Comment by Amyh11325** [comment]
Should I filter the live feed and good first issues too? Imo it's ok for the live feed to show everything, but I'm not sure if the good first issues tag is used exclusively for open source projects.

**Comment by ArshMalik02** [comment]
> Should I filter the live feed and good first issues too? Imo it's ok for the live feed to show everything, but I'm not sure if the good first issues tag is used exclusively for open source projects.

@Amyh11325 we should filter the good first issues to be only coming from repos that have `ucla-opensource` as one of the topics. We can leave the live feed as is. Check out this issue #156 that details the tasks we need to do to make this transition.

You can modify this PR to meet the two tasks- filter the repos and filter the good first issues.

Let me know if you have any questions!

**Comment by Amyh11325** [comment]
> > Should I filter the live feed and good first issues too? Imo it's ok for the live feed to show everything, but I'm not sure if the good first issues tag is used exclusively for open source projects.
> 
> @Amyh11325 we should filter the good first issues to be only coming from repos that have `ucla-opensource` as one of the topics. We can leave the live feed as is. Check out this issue #156 that details the tasks we need to do to make this transition.
> 
> You can modify this PR to meet the two tasks- filter the repos and filter the good first issues.
> 
> Let me know if you have any questions!

Done!

**Comment by ArshMalik02** [comment]
> > > Should I filter the live feed and good first issues too? Imo it's ok for the live feed to show everything, but I'm not sure if the good first issues tag is used exclusively for open source projects.
> > 
> > 
> > @Amyh11325 we should filter the good first issues to be only coming from repos that have `ucla-opensource` as one of the topics. We can leave the live feed as is. Check out this issue #156 that details the tasks we need to do to make this transition.
> > You can modify this PR to meet the two tasks- filter the repos and filter the good first issues.
> > Let me know if you have any questions!
> 
> Done!

@Amyh11325 I noticed that the projects page lists a subset of repos that are listed here (https://github.com/topics/ucla-opensource). Can we introduce a change that lists all the ucla-opensource repos and not only those owned by ACM?

**Comment by Amyh11325** [comment]
> > > > Should I filter the live feed and good first issues too? Imo it's ok for the live feed to show everything, but I'm not sure if the good first issues tag is used exclusively for open source projects.
> > > 
> > > 
> > > @Amyh11325 we should filter the good first issues to be only coming from repos that have `ucla-opensource` as one of the topics. We can leave the live feed as is. Check out this issue #156 that details the tasks we need to do to make this transition.
> > > You can modify this PR to meet the two tasks- filter the repos and filter the good first issues.
> > > Let me know if you have any questions!
> > 
> > 
> > Done!
> 
> @Amyh11325 I noticed that the projects page lists a subset of repos that are listed here (https://github.com/topics/ucla-opensource). Can we introduce a change that lists all the ucla-opensource repos and not only those owned by ACM?

Done!
Screen Shot 2024-03-04 at 2 08 24 PM

**Comment by Amyh11325** [comment]
Should the good first issues page also include repos outside the uclaacm org? I believe it's limited to uclaacm right now

**Comment by ArshMalik02** [comment]
> Should the good first issues page also include repos outside the uclaacm org? I believe it's limited to uclaacm right now

Yes, since we are expanding the entire project to all ucla projects

**Comment by ArshMalik02** [comment]
> > > > > Should I filter the live feed and good first issues too? Imo it's ok for the live feed to show everything, but I'm not sure if the good first issues tag is used exclusively for open source projects.
> > > > 
> > > > 
> > > > @Amyh11325 we should filter the good first issues to be only coming from repos that have `ucla-opensource` as one of the topics. We can leave the live feed as is. Check out this issue #156 that details the tasks we need to do to make this transition.
> > > > You can modify this PR to meet the two tasks- filter the repos and filter the good first issues.
> > > > Let me know if you have any questions!
> > > 
> > > 
> > > Done!
> > 
> > 
> > @Amyh11325 I noticed that the projects page lists a subset of repos that are listed here (https://github.com/topics/ucla-opensource). Can we introduce a change that lists all the ucla-opensource repos and not only those owned by ACM?
> 
> Done! Screen Shot 2024-03-04 at 2 08 24 PM

can we not have the default image as the acm logo for the projects that are not owned by acm?

**Comment by ArshMalik02** [comment]
> > > > > > > Should I filter the live feed and good first issues too? Imo it's ok for the live feed to show everything, but I'm not sure if the good first issues tag is used exclusively for open source projects.
> > > > > > 
> > > > > > 
> > > > > > @Amyh11325 we should filter the good first issues to be only coming from repos that have `ucla-opensource` as one of the topics. We can leave the live feed as is. Check out this issue #156 that details the tasks we need to do to make this transition.
> > > > > > You can modify this PR to meet the two tasks- filter the repos and filter the good first issues.
> > > > > > Let me know if you have any questions!
> > > > > 
> > > > > 
> > > > > Done!
> > > > 
> > > > 
> > > > @Amyh11325 I noticed that the projects page lists a subset of repos that are listed here (https://github.com/topics/ucla-opensource). Can we introduce a change that lists all the ucla-opensource repos and not only those owned by ACM?
> > > 
> > > 
> > > Done! Screen Shot 2024-03-04 at 2 08 24 PM
> > 
> > 
> > can we not have the default image as the acm logo for the projects that are not owned by acm?
> 
> What should the image be then?

That's a good question! We don't have an asset for it, but if you have any recs for a default image like a stock image or something, we can explore that option.

**Comment by Amyh11325** [comment]
Ok I replaced it with the ucla logo and I updated the good first issues too
Screen Shot 2024-03-04 at 2 37 06 PM

**Comment by ArshMalik02** [comment]
> Ok I replaced it with the ucla logo and I updated the good first issues too Screen Shot 2024-03-04 at 2 37 06 PM

great! lgtm, approving this request and merging.

**Review by ArshMalik02 — APPROVED** [review]
lgtm

**Pull request merged**
