### PR TITLE
fix: remove sinon and enable image preload for random project

### PR DESCRIPTION
**Pull request by reginawang3495**
follow-up from: #77, #33

### CODE REVIEW

**Comment by reginawang3495** [comment]
Ready for review, if anyone would like to review this :))

**Review by mattxwang — APPROVED** [review]
Great work!

**Comment by mattxwang** [comment]
Screen Shot 2022-01-24 at 2 20 52 PM

Also, just noticed that the color for the language is not consistent (this is flaky behaviour) - do you think this followed #33?

**Comment by reginawang3495** [comment]
@mattxwang I think it's fine at least after this PR? I tried it on local env

**Pull request merged**
